# Generated by Django 2.2.3 on 2020-01-16 02:59

from django.db import migrations
from django.conf import settings
import phonenumbers


def set_owner_phone_pure_from_owners_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_number = phonenumbers.parse(
            flat.owners_phonenumber, settings.PHONENUMBER_DEFAULT_REGION)
        flat.owner_phone_pure = phonenumbers.format_number(
            phone_number, phonenumbers.PhoneNumberFormat.E164) if (
        phonenumbers.is_valid_number(phone_number)) else ''
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_phone_pure = ''
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(set_owner_phone_pure_from_owners_phonenumber, move_backward)
    ]
