# Generated by Django 2.2.3 on 2020-01-17 16:39

from django.db import migrations


def set_owner_from_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            full_name=flat.owner,
            phone_pure=flat.owner_phone_pure,
            defaults={
                'phonenumber': flat.owners_phonenumber,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(set_owner_from_flat)
    ]
