# Generated by Django 2.2.3 on 2020-01-17 18:12

from django.db import migrations

def set_owners_flats_from_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            full_name=flat.owner,
            phone_pure=flat.owner_phone_pure,
            defaults={
                'phonenumber': flat.owners_phonenumber,
            }
        )
        flat.owners.add(owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20200117_2110'),
    ]

    operations = [
        migrations.RunPython(set_owners_flats_from_flat)
    ]
